Areas/Admin/Controllers/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using ProjectMVC_Ecommerce.Helper;
using ProjectMVC_Ecommerce.Models;

namespace ProjectMVC_Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminProductsController : Controller
    {
        private readonly dbMarketsContext _context;
        public INotyfService _notyfService { get; set; }

        public AdminProductsController(dbMarketsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminProducts
        public IActionResult Index(int page = 1, int CatID = 0)
        {
            int pageSize = 10;
            IQueryable<Product> query = _context.Products
                .AsNoTracking()
                .Include(x => x.Cat)
                .OrderByDescending(x => x.ProductId); // Đặt trình tự ban đầu

            if (CatID != 0)
            {
                query = query.Where(x => x.CatId == CatID)
                             .OrderByDescending(x => x.ProductId); // Thêm trình tự nếu cần
            }

            var models = new PagedList<Product>(query, page, pageSize);

            ViewBag.CurrentCateID = CatID;
            ViewBag.CurrentPage = page;
            ViewBag.Categories = _context.Categories.ToList();

            return View(models);
        }



        public IActionResult Filter(int CatID = 0)
        {
            var url = $"/Admin/AdminProducts?CatID={CatID}";
            if (CatID == 0)
            {
                url = "/Admin/AdminProducts";
            }
            return Json(new { status = "success", redirectUrl = url });
        }



        // GET: Admin/AdminProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Admin/AdminProducts/Create
        public IActionResult Create()
        {
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName");
            return View();
        }

        // POST: Admin/AdminProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ShortDesc,Description,CatId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetaKey,UnitsInStock")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                product.ProductName = Utilities.ToTitleCase(product.ProductName);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(product.ProductName) + extension;
                    product.Thumb = await Utilities.UploadFile(fThumb, @"products", image.ToLower());
                }
                if (string.IsNullOrEmpty(product.Thumb)) product.Thumb = "default.jpg";
                product.Alias = Utilities.SEOUrl(product.ProductName);
                product.DateModified = DateTime.Now;
                product.DateCreated = DateTime.Now;
                _context.Add(product);
                await _context.SaveChangesAsync();
                _notyfService.Success("Add Success");
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatId", product.CatId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        // POST: Admin/AdminProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ShortDesc,Description,CatId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetaKey,UnitsInStock")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    product.ProductName = Utilities.ToTitleCase(product.ProductName);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(product.ProductName) + extension;
                        product.Thumb = await Utilities.UploadFile(fThumb, @"products", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(product.Thumb)) product.Thumb = "default.jpg";
                    product.Alias = Utilities.SEOUrl(product.ProductName);
                    product.DateModified = DateTime.Now;
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Update Success");

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Admin/AdminProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'dbMarketsContext.Products'  is null.");
            }
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
                _notyfService.Success("Delete Success");

            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return (_context.Products?.Any(e => e.ProductId == id)).GetValueOrDefault();
        }


    }
}

Areas/Admin/Views/AdminProducts/Create.cshtml
@model ProjectMVC_Ecommerce.Models.Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<form asp-controller="AdminProducts" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary" id="testButton">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Product Name</label>
                        <input type="text" class="form-control" asp-for="ProductName">
                    </div><div class="form-group">
                        <label class="font-weight-semibold" for="productName">Short desc</label>
                        <input type="text" class="form-control" asp-for="ShortDesc">
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productPrice">Price</label>
                            <input type="text" class="form-control" asp-for="Price">
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productPrice">Price Discount</label>
                            <input type="text" class="form-control" asp-for="Discount">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productName">UnitsInStock</label>
                            <input type="text" class="form-control" asp-for="UnitsInStock">
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productCategory">Category</label>
                            <select class="custom-select" asp-for="CatId" style="min-width: 180px;" asp-items="ViewBag.CatId">
                                <option selected disabled>Select Category</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Thumnail</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div>
                        <div class="checkbox">
                            <input type="checkbox" asp-for="Active">
                            <label for="Active">Public</label>
                        </div>
                        <div class="checkbox">
                            <input type="checkbox" asp-for="HomeFlag">
                            <label for="HomeFlag">HomeFlag</label>
                        </div>
                        <div class="checkbox">
                            <input type="checkbox" asp-for="BestSellers">
                            <label for="BestSellers">BestSellers</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc" />

                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey" />

                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">Tags</label>
                        <input type="text" class="form-control" asp-for="Tags" />

                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <div id="productDescription">
                        <div id="editor-container"></div>
                    </div>
                    <input type="hidden" asp-for="Description" id="Description" />
                </div>
            </div>
        </div>


    </div>
</form>


@section Scripts {
    <!-- page js -->
    <script src="~/AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/AdminAssets/vendors/quill/quill.min.js"></script>
    <script src="~/AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script>
        // e-commerce-product-edit.js

        // Initialize Quill
        var quill = new Quill('#editor-container', {
            theme: 'snow' // or 'bubble' for more compact toolbar
        });

        // Update the hidden input field when the form is submitted
        $('form').on('submit', function () {
            var description = document.querySelector('.ql-editor').innerHTML;
            $('#Description').val(description);
        });

    </script>
}
    

Areas/Admin/Views/AdminProducts/Delete.cshtml
@model ProjectMVC_Ecommerce.Models.Product

@{
    ViewData["Title"] = "Details" + Model.ProductName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-controller="AdminProducts" asp-action="Index">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Chi tiết sản phẩm : @Model.ProductName</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Chi tiết sản phẩm : @Model.ProductName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.ProductId</td>
                    </tr>
                    <tr>
                        <td>Name:</td>
                        <td>@Model.ProductName</td>
                    </tr>
                    <tr>
                        <td>Short Description:</td>
                        <td>@Model.ShortDesc</td>
                    </tr>
                    <tr>
                        <td>Price:</td>
                        <td>@Model.Price</td>
                    </tr>
                    <tr>
                        <td>Active:</td>
                        <td>
                            <div class="checkbox">
                                <input id="checkbox2" type="checkbox" @(Model.Active ? "checked" : "") disabled>
                                <label for="checkbox2">Active</label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>BestSellers:</td>
                        <td>
                            <div class="checkbox">
                                <input id="checkbox1" type="checkbox" @(Model.BestSellers ? "checked" : "") disabled>
                                <label for="checkbox1">BestSellers</label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>HomeFlag:</td>
                        <td>
                            <div class="checkbox">
                                <input id="checkbox2" type="checkbox" @(Model.HomeFlag ? "checked" : "") disabled>
                                <label for="checkbox2">HomeFlag</label>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>Discount:</td>
                        <td>@Model.Discount</td>
                    </tr>
                    <tr>
                        <td>Category:</td>
                        <td>@Model.Cat.CatName</td>
                    </tr>
                    <tr>
                        <td>DateCreated:</td>
                        <td>@Model.DateCreated</td>
                    </tr>
                    <tr>
                        <td>DateModified:</td>
                        <td>@Model.DateModified</td>
                    </tr>
                    <tr>
                        <td>Title:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>
                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    <tr>
                        <td>Tags:</td>
                        <td>@Model.Tags</td>
                    </tr>
                    <tr>
                        <td>Thumbnails:</td>
                        <td><img width="200" height="200" src="~/images/products/@Model.Thumb" /></td>
                    </tr>
                    <tr>
                        <td>Description:</td>
                        <td>
                            @Html.Raw(Model.Description)
                        </td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa:</td>
                        <td>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="ProductId" />
                                <input type="submit" value="Delete" class="btn btn-danger" /> |
                                <a asp-action="Index">Back to List</a>
                            </form>
                        </td>
                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminProducts/Details.cshtml
@model ProjectMVC_Ecommerce.Models.Product

@{
    ViewData["Title"] = "Details" + Model.ProductName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-controller="AdminProducts" asp-action="Index">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Chi tiết sản phẩm : @Model.ProductName</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Chi tiết sản phẩm : @Model.ProductName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.ProductId</td>
                    </tr>
                    <tr>
                        <td>Name:</td>
                        <td>@Model.ProductName</td>
                    </tr>
                    <tr>
                        <td>Short Description:</td>
                        <td>@Model.ShortDesc</td>
                    </tr>
                    <tr>
                        <td>Price:</td>
                        <td>@Model.Price</td>
                    </tr>
                    <tr>
                        <td>Active:</td>
                        <td>
                            <div class="checkbox">
                                <input id="checkbox2" type="checkbox" @(Model.Active ? "checked" : "") disabled>
                                <label for="checkbox2">Active</label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>BestSellers:</td>
                        <td>
                            <div class="checkbox">
                                <input id="checkbox1" type="checkbox" @(Model.BestSellers ? "checked" : "") disabled>
                                <label for="checkbox1">BestSellers</label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>HomeFlag:</td>
                        <td>
                            <div class="checkbox">
                                <input id="checkbox2" type="checkbox" @(Model.HomeFlag ? "checked" : "") disabled>
                                <label for="checkbox2">HomeFlag</label>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>Discount:</td>
                        <td>@Model.Discount</td>
                    </tr>
                    <tr>
                        <td>Category:</td>
                        <td>@Model.Cat.CatName</td>
                    </tr>
                    <tr>
                        <td>DateCreated:</td>
                        <td>@Model.DateCreated</td>
                    </tr>
                    <tr>
                        <td>DateModified:</td>
                        <td>@Model.DateModified</td>
                    </tr>
                    <tr>
                        <td>Title:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>
                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    <tr>
                        <td>Tags:</td>
                        <td>@Model.Tags</td>
                    </tr>
                    <tr>
                        <td>Thumbnails:</td>
                        <td><img width="200" height="200" src="~/images/products/@Model.Thumb" /></td>
                    </tr>
                    <tr>
                        <td>Description:</td>
                        <td>
                            @Html.Raw(Model.Description)
                        </td>
                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>