Areas/Admin/Controllers/AdminPagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using ProjectMVC_Ecommerce.Helper;
using ProjectMVC_Ecommerce.Models;

namespace ProjectMVC_Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminPagesController : Controller
    {
        private readonly dbMarketsContext _context;
        public INotyfService _notyfService { get; set; }

        public AdminPagesController(dbMarketsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminPages
        public async Task<IActionResult> Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsPages = _context.Pages.AsNoTracking()
                .OrderByDescending(x => x.PageId);
            PagedList<Page> models = new PagedList<Page>(lsPages, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;

            return View(models);
        }

        // GET: Admin/AdminPages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pages == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // GET: Admin/AdminPages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PageId,PageName,Contents,Thumb,Published,Title,MetaDesc,MetaKey,Alias,CreatedDate,Ordering")] Page page, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                page.PageName = Utilities.ToTitleCase(page.PageName);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(page.PageName) + extension;
                    page.Thumb = await Utilities.UploadFile(fThumb, @"pages", image.ToLower());
                }
                else
                {
                    page.Thumb = "default.jpg"; 
                }
                page.Alias = Utilities.SEOUrl(page.PageName);
                page.CreatedDate = DateTime.Now;
                _context.Add(page);
                await _context.SaveChangesAsync();
                _notyfService.Success("Add Success");
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pages == null)
            {
                return NotFound();
            }

            var page = await _context.Pages.FindAsync(id);
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

        // POST: Admin/AdminPages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PageId,PageName,Contents,Thumb,Published,Title,MetaDesc,MetaKey,Alias,CreatedDate,Ordering")] Page page, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != page.PageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    page.PageName = Utilities.ToTitleCase(page.PageName);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(page.PageName) + extension;
                        page.Thumb = await Utilities.UploadFile(fThumb, @"pages", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                    page.Alias = Utilities.SEOUrl(page.PageName);
                    page.CreatedDate = DateTime.Now;
                    _context.Update(page);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Edit Success");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PageExists(page.PageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pages == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // POST: Admin/AdminPages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pages == null)
            {
                return Problem("Entity set 'dbMarketsContext.Pages'  is null.");
            }
            var page = await _context.Pages.FindAsync(id);
            if (page != null)
            {
                _context.Pages.Remove(page);
            }
            
            await _context.SaveChangesAsync();
            _notyfService.Success("Delete Success");
            return RedirectToAction(nameof(Index));
        }

        private bool PageExists(int id)
        {
          return (_context.Pages?.Any(e => e.PageId == id)).GetValueOrDefault();
        }
    }
}

Areas/Admin/Views/AdminPages/Create.cshtml
@model ProjectMVC_Ecommerce.Models.Page

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<form asp-controller="AdminPages" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary" id="testButton">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Page Name</label>
                        <input type="text" class="form-control" asp-for="PageName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ordering">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                        <span asp-validation-for="Ordering" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Thumnail</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div>
                        <div class="checkbox">
                            <input type="checkbox" asp-for="Published">
                            <label for="Published">Published</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc" />

                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey" />

                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <div id="productDescription">
                        <div id="editor-container"></div>
                    </div>
                    <input type="hidden" asp-for="Contents" id="Description" />
                </div>
            </div>
        </div>

    </div>
</form>


@section Scripts {
    <!-- page js -->
    <script src="~/AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/AdminAssets/vendors/quill/quill.min.js"></script>
    <script src="~/AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script>
        // e-commerce-product-edit.js

        // Initialize Quill
        var quill = new Quill('#editor-container', {
            theme: 'snow' // or 'bubble' for more compact toolbar
        });

        // Update the hidden input field when the form is submitted
        $('form').on('submit', function () {
            var description = document.querySelector('.ql-editor').innerHTML;
            $('#Description').val(description);

        });

    </script>
}

Areas/Admin/Views/AdminPages/Delete.cshtml
@model ProjectMVC_Ecommerce.Models.Page

@{
    ViewData["Title"] = "Details" + Model.PageName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-controller="AdminProducts" asp-action="Index">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Chi tiết sản phẩm : @Model.PageName</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Chi tiết sản phẩm : @Model.PageName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.PageId</td>
                    </tr>
                    <tr>
                        <td>Name:</td>
                        <td>@Model.PageName</td>
                    </tr>
                    <tr>
                        <td>Contents:</td>
                        <td>
                            @Html.Raw(Model.Contents)
                        </td>
                    </tr>
                    <tr>
                        <td>Thumbnails:</td>
                        <td><img width="200" height="200" src="~/images/pages/@Model.Thumb" /></td>
                    </tr>
                    <tr>
                        <td>Published:</td>
                        <td>
                            <div class="checkbox">
                                <input id="checkbox2" type="checkbox" @(Model.Published ? "checked" : "") disabled>
                                <label for="checkbox2">Published</label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Title:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>
                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    <tr>
                        <td>Alias:</td>
                        <td>@Model.Alias</td>
                    </tr>
                    <tr>
                        <td>CreatedDate:</td>
                        <td>@Model.CreatedDate</td>
                    </tr>
                    <tr>
                        <td>Ordering:</td>
                        <td>@Model.Ordering</td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa:</td>
                        <td>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="PageId" />
                                <input type="submit" value="Delete" class="btn btn-danger" /> |
                                <a asp-action="Index">Back to List</a>
                            </form>
                        </td>
                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/AdminPages/Details.cshtml
@model ProjectMVC_Ecommerce.Models.Page

@{
    ViewData["Title"] = "Details" + Model.PageName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-controller="AdminProducts" asp-action="Index">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Chi tiết sản phẩm : @Model.PageName</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Chi tiết sản phẩm : @Model.PageName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.PageId</td>
                    </tr>
                    <tr>
                        <td>Name:</td>
                        <td>@Model.PageName</td>
                    </tr>
                    <tr>
                        <td>Contents:</td>
                        <td>
                            @Html.Raw(Model.Contents)
                        </td>
                    </tr>
                    <tr>
                        <td>Thumbnails:</td>
                        <td><img width="200" height="200" src="~/images/pages/@Model.Thumb" /></td>
                    </tr>
                    <tr>
                        <td>Published:</td>
                        <td>
                            <div class="checkbox">
                                <input id="checkbox2" type="checkbox" @(Model.Published ? "checked" : "") disabled>
                                <label for="checkbox2">Published</label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Title:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>
                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    <tr>
                        <td>Alias:</td>
                        <td>@Model.Alias</td>
                    </tr>
                    <tr>
                        <td>CreatedDate:</td>
                        <td>@Model.CreatedDate</td>
                    </tr>
                    <tr>
                        <td>Ordering:</td>
                        <td>@Model.Ordering</td>
                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminPages/Edit.cshtml
@model ProjectMVC_Ecommerce.Models.Page

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<form asp-controller="AdminPages" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="PageId" />
    <input type="hidden" asp-for="Thumb" />
    <input type="hidden" asp-for="CreatedDate" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary" id="testButton">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Page Name</label>
                        <input type="text" class="form-control" asp-for="PageName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ordering">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                        <span asp-validation-for="Ordering" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Thumbnail</label>
                        <input name="fThumb" type="file" class="form-control-file" id="thumbInput" asp-for="Thumb" />
                        <span id="fileNameSpan"></span>
                        @if (!string.IsNullOrEmpty(Model.Thumb))
                        {
                            <div class="existing-thumbnail">
                                <img width="200" height="200" src="~/images/pages/@Model.Thumb" />
                            </div>
                        }
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div>
                        <div class="checkbox">
                            <input type="checkbox" asp-for="Published">
                            <label for="Published">Published</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc" />

                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey" />

                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <div id="productDescription">
                        <div id="editor-container">@Html.Raw(Model.Contents)</div>
                    </div>
                    <input type="hidden" asp-for="Contents" id="Description" />
                </div>
            </div>
        </div>

    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <!-- page js -->
    <script src="~/AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/AdminAssets/vendors/quill/quill.min.js"></script>
    <script src="~/AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script>
        // Initialize Quill
        // Initialize Quill
        var quill = new Quill('#editor-container', {
            theme: 'snow' // or 'bubble' for more compact toolbar
        });

        // Update the hidden input field when the form is submitted
        $('form').on('submit', function () {
            var description = document.querySelector('.ql-editor').innerHTML;
            $('#Description').val(description);

            // Kiểm tra xem người dùng đã chọn tập tin mới hay chưa
            var fileSelected = false;
            if ($('#thumbInput').prop('files')[0]) {
                fileSelected = true;
            }

            // Nếu người dùng chưa chọn tập tin mới, giữ tên file cũ
            if (!fileSelected) {
                var currentFileName = $('#thumbInput').attr('data-initial-value'); // Lấy giá trị ban đầu từ data attribute
                $('#thumbInput').val(currentFileName);
            }
        });

        // Xử lý khi người dùng chọn file
        document.querySelector('#thumbInput').addEventListener('change', function (event) {
            var fileName = event.target.files[0].name;
            document.querySelector('#fileNameSpan').textContent = fileName;
        });

        // Nếu đã có file được chọn trước đó, hiển thị tên file
        var initialFileName = '@Model.Thumb';
        if (initialFileName) {
            document.querySelector('#fileNameSpan').textContent = initialFileName;
            $('#thumbInput').attr('data-initial-value', initialFileName); // Lưu giá trị ban đầu vào data attribute
        }

    </script>
}

Areas/Admin/Views/AdminPages/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<ProjectMVC_Ecommerce.Models.Page>
@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách Page " + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" href="#">Apps</a>
            <a class="breadcrumb-item" href="#">E-commerce</a>
            <span class="breadcrumb-item active">Customers List : page @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class="d-md-flex">
                    <div class="m-b-10 m-r-15">
                        <select class="custom-select" style="min-width: 180px;">
                            <option selected>Catergory</option>
                            <option value="all">All</option>
                            <option value="homeDeco">Home Decoration</option>
                            <option value="eletronic">Eletronic</option>
                            <option value="jewellery">Jewellery</option>
                        </select>
                    </div>
                    <div class="m-b-10">
                        <select class="custom-select" style="min-width: 180px;">
                            <option selected>Status</option>
                            <option value="all">All</option>
                            <option value="inStock">In Stock </option>
                            <option value="outOfStock">Out of Stock</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminPages" asp-action="Create">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Add Pages</span>
                </a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>PageName</th>
                        <th>Status</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            string url = $"/page/{item.Alias}";
                            <tr>
                                <td>@item.PageId</td>
                                <td>
                                    <a href="@url">
                                        @item.PageName
                                    </a>
                                    
                                </td>
                                <td>
                                    @if(item.Published == true)
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Public</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Non Public</div>
                                        </div>
                                    }
                                </td>
                                <td>
                                    <a asp-area="Admin" asp-controller="AdminPages" asp-action="Details" asp-route-id="@item.PageId" class="btn btn-primary btn-tone m-r-5">View</a>
                                    <a asp-area="Admin" asp-controller="AdminPages" asp-action="Edit" asp-route-id="@item.PageId" class="btn btn-secondary btn-tone m-r-5">Edit</a>
                                    <a asp-area="Admin" asp-controller="AdminPages" asp-action="Delete" asp-route-id="@item.PageId" class="btn btn-success btn-tone m-r-5">Delete</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminPages" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>