Areas/Admin/Controllers/AdminTinDangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using ProjectMVC_Ecommerce.Helper;
using ProjectMVC_Ecommerce.Models;

namespace ProjectMVC_Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminTinDangsController : Controller
    {
        private readonly dbMarketsContext _context;
        public INotyfService _notyfService { get; set; }

        public AdminTinDangsController(dbMarketsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminTinDangs
        public async Task<IActionResult> Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;
            var lsTinDangs = _context.TinDangs.AsNoTracking()
                .OrderByDescending(x => x.PostId);
            PagedList<TinDang> models = new PagedList<TinDang>(lsTinDangs, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;

            return View(models);
        }

        // GET: Admin/AdminTinDangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TinDangs == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (tinDang == null)
            {
                return NotFound();
            }

            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminTinDangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreatedDate,Author,AccountId,Tags,CatId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] TinDang tinDang, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                tinDang.Title = Utilities.ToTitleCase(tinDang.Title);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(tinDang.Title) + extension;
                    tinDang.Thumb = await Utilities.UploadFile(fThumb, @"news", image.ToLower());
                }
                if (string.IsNullOrEmpty(tinDang.Thumb)) tinDang.Thumb = "default.jpg";
                tinDang.Alias = Utilities.SEOUrl(tinDang.Title);
                tinDang.CreatedDate = DateTime.Now;
                _context.Add(tinDang);
                await _context.SaveChangesAsync();
                _notyfService.Success("Add Success");
                return RedirectToAction(nameof(Index));
            }
            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TinDangs == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs.FindAsync(id);
            if (tinDang == null)
            {
                return NotFound();
            }
            return View(tinDang);
        }

        // POST: Admin/AdminTinDangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreatedDate,Author,AccountId,Tags,CatId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] TinDang tinDang, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != tinDang.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    tinDang.Title = Utilities.ToTitleCase(tinDang.Title);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(tinDang.Title) + extension;
                        tinDang.Thumb = await Utilities.UploadFile(fThumb, @"news", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(tinDang.Thumb)) tinDang.Thumb = "default.jpg";
                    tinDang.Alias = Utilities.SEOUrl(tinDang.Title);
                    tinDang.CreatedDate = DateTime.Now;
                    _context.Update(tinDang);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Update Success");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TinDangExists(tinDang.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TinDangs == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (tinDang == null)
            {
                return NotFound();
            }

            return View(tinDang);
        }

        // POST: Admin/AdminTinDangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TinDangs == null)
            {
                return Problem("Entity set 'dbMarketsContext.TinDangs'  is null.");
            }
            var tinDang = await _context.TinDangs.FindAsync(id);
            if (tinDang != null)
            {
                _context.TinDangs.Remove(tinDang);
                _notyfService.Success("Delete Success");

            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TinDangExists(int id)
        {
            return (_context.TinDangs?.Any(e => e.PostId == id)).GetValueOrDefault();
        }
    }
}

Areas/Admin/Views/AdminTinDangs/Create.cshtml
@model ProjectMVC_Ecommerce.Models.TinDang

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<form asp-controller="AdminTinDangs" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary" id="testButton">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tiltle</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Short content</label>
                        <input type="text" class="form-control" asp-for="Scontents">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Thumnail</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div>
                        <div class="checkbox">
                            <input type="checkbox" asp-for="Published">
                            <label for="Published">Published</label>
                        </div>
                        <div class="checkbox">
                            <input type="checkbox" asp-for="IsHot">
                            <label for="IsHot">IsHot</label>
                        </div><div class="checkbox">
                            <input type="checkbox" asp-for="IsNewfeed">
                            <label for="IsNewfeed">IsNewfeed</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc" />

                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">Tags</label>
                        <input type="text" class="form-control" asp-for="Tags" />
                    </div>

                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <div id="productDescription">
                        <div id="editor-container"></div>
                    </div>
                    <input type="hidden" asp-for="Contents" id="Description" />
                </div>
            </div>
        </div>

    </div>
</form>


@section Scripts {
    <!-- page js -->
    <script src="~/AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/AdminAssets/vendors/quill/quill.min.js"></script>
    <script src="~/AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script>
        // e-commerce-product-edit.js

        // Initialize Quill
        var quill = new Quill('#editor-container', {
            theme: 'snow' // or 'bubble' for more compact toolbar
        });

        // Update the hidden input field when the form is submitted
        $('form').on('submit', function () {
            var description = document.querySelector('.ql-editor').innerHTML;
            $('#Description').val(description);
        });

    </script>
}

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminTinDangs/Delete.cshtml
@model ProjectMVC_Ecommerce.Models.TinDang

@{
    ViewData["Title"] = "Details" + Model.Title;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-controller="AdminTinDangs" asp-action="Index">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Chi tiết sản phẩm : @Model.Title</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Chi tiết sản phẩm : @Model.Title</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.PostId</td>
                    </tr>
                    <tr>
                        <td>Name:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>Contents:</td>
                        <td>
                            @Html.Raw(Model.Contents)
                        </td>
                    </tr>
                    <tr>
                        <td>Thumbnails:</td>
                        <td><img width="200" height="200" src="~/images/news/@Model.Thumb" /></td>
                    </tr>
                    <tr>
                        <td>Published:</td>
                        <td>
                            <div class="checkbox">
                                <input id="checkbox2" type="checkbox" @(Model.Published ? "checked" : "") disabled>
                                <label for="checkbox2">Published</label>
                            </div>
                            <div class="checkbox">
                                <input id="checkbox2" type="checkbox" @(Model.IsHot ? "checked" : "") disabled>
                                <label for="checkbox2">IsHot</label>
                            </div><div class="checkbox">
                                <input id="checkbox2" type="checkbox" @(Model.IsNewfeed ? "checked" : "") disabled>
                                <label for="checkbox2">IsNewfeed</label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Title:</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr>
                        <td>MetaDesc:</td>
                        <td>@Model.MetaDesc</td>
                    </tr>
                    <tr>
                        <td>MetaKey:</td>
                        <td>@Model.MetaKey</td>
                    </tr>
                    <tr>
                        <td>Alias:</td>
                        <td>@Model.Alias</td>
                    </tr>
                    <tr>
                        <td>Tags:</td>
                        <td>@Model.Tags</td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa :</td>
                        <td>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="PostId" />
                                <input type="submit" value="Delete" class="btn btn-danger" /> |
                                <a asp-action="Index">Back to List</a>
                            </form>
                        </td>
                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>


    
    

Areas/Admin/Views/AdminTinDangs/Details.cshtml
@model ProjectMVC_Ecommerce.Models.TinDang

@{
    ViewData["Title"] = "Details" + Model.Title;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-controller="AdminTinDangs" asp-action="Index">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Chi tiết sản phẩm : @Model.Title</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-md-center justify-content-between">
        <div class="media m-b-15 align-items-center">
            <div class="avatar avatar-image rounded" style="height : 70px;width: 70px">
                <img src="~/images/news/@Model.Thumb" alt="@Model.Thumb">
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.Title</h4>
                <p class="text-muted m-b-0">ID: #@Model.PostId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Edit" asp-route-id="@Model.PostId">
                <span>Edit</span>
            </a>
        </div>
    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-edit-option">Image Info</a>
        </li>
    </ul>
</div>

<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Chi tiết sản phẩm : @Model.Title</h4>
                    <div class="table-responsive">
                        <table class="product-info-table m-t-20">
                            <tbody>
                                <tr>
                                    <td>Name:</td>
                                    <td>@Model.Title</td>
                                </tr>
                                <tr>
                                    <td>Alias:</td>
                                    <td>@Model.Alias</td>
                                </tr>

                                <tr>
                                    <td>Stastus:</td>
                                    <td>
                                        <div class="checkbox">
                                            <input id="checkbox2" type="checkbox" @(Model.Published ? "checked" : "") disabled>
                                            <label for="checkbox2">Published</label>
                                        </div>
                                        <div class="checkbox">
                                            <input id="checkbox2" type="checkbox" @(Model.IsHot ? "checked" : "") disabled>
                                            <label for="checkbox2">IsHot</label>
                                        </div><div class="checkbox">
                                            <input id="checkbox2" type="checkbox" @(Model.IsNewfeed ? "checked" : "") disabled>
                                            <label for="checkbox2">IsNewfeed</label>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thông tin mô tả</h4>
                </div>
                <div class="card-body">
                    @Html.Raw(Model.Contents)
                </div>
            </div>
            </div>
            
            <div class="tab-pane fade" id="product-edit-option">
                <div class="card">
                    <div class="card-body">
                       <div class="row">
                           <div class="col-md-12">
                               <img  class="img-fluid" src="~/images/news/@Model.Thumb" alt="@Model.Title"/>
                           </div>
                       </div>
                    </div>
                </div>
            </div>
        </div>
      
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminTinDangs/Edit.cshtml
@model ProjectMVC_Ecommerce.Models.TinDang

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<form asp-controller="AdminTinDangs" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="PostId" />
    <input type="hidden" asp-for="CreatedDate" />
    <input type="hidden" asp-for="Thumb" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary" id="testButton">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tiltle</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Short content</label>
                        <input type="text" class="form-control" asp-for="Scontents">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Thumnail</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div>
                        <div class="checkbox">
                            <input type="checkbox" asp-for="Published">
                            <label for="Published">Published</label>
                        </div>
                        <div class="checkbox">
                            <input type="checkbox" asp-for="IsHot">
                            <label for="Published">IsHot</label>
                        </div><div class="checkbox">
                            <input type="checkbox" asp-for="IsNewfeed">
                            <label for="Published">IsNewfeed</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc" />

                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">Tags</label>
                        <input type="text" class="form-control" asp-for="Tags" />
                    </div>

                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <div id="productDescription">
                        <div id="editor-container">@Html.Raw(Model.Contents)</div>
                    </div>
                    <input type="hidden" asp-for="Contents" id="Description" />
                </div>
            </div>
        </div>

    </div>
</form>


@section Scripts {
    <!-- page js -->
    <script src="~/AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/AdminAssets/vendors/quill/quill.min.js"></script>
    <script src="~/AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script>
        // e-commerce-product-edit.js

        // Initialize Quill
        var quill = new Quill('#editor-container', {
            theme: 'snow' // or 'bubble' for more compact toolbar
        });

        // Update the hidden input field when the form is submitted
        $('form').on('submit', function () {
            var description = document.querySelector('.ql-editor').innerHTML;
            $('#Description').val(description);
        });

    </script>
}

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminTinDangs/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<ProjectMVC_Ecommerce.Models.TinDang>
@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách Post " + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" href="#">Apps</a>
            <a class="breadcrumb-item" href="#">E-commerce</a>
            <span class="breadcrumb-item active">Customers List : page @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class="d-md-flex">
                    <div class="m-b-10 m-r-15">
                        <select class="custom-select" style="min-width: 180px;">
                            <option selected>Catergory</option>
                            <option value="all">All</option>
                            <option value="homeDeco">Home Decoration</option>
                            <option value="eletronic">Eletronic</option>
                            <option value="jewellery">Jewellery</option>
                        </select>
                    </div>
                    <div class="m-b-10">
                        <select class="custom-select" style="min-width: 180px;">
                            <option selected>Status</option>
                            <option value="all">All</option>
                            <option value="inStock">In Stock </option>
                            <option value="outOfStock">Out of Stock</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminTinDangs" asp-action="Create">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Add News</span>
                </a>
            </div>

        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>PostTitle</th>
                        <th>CretedDate</th>
                        <th>Published</th>
                        <th>Hot</th>
                        <th>Newfeed</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.PostId</td>
                                <td>@item.Title</td>
                                <td>@item.CreatedDate</td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <div class="badge @(item.Published ? "badge-success" : "badge-dark") badge-dot m-r-10"></div>
                                        <div>Published</div>
                                    </div>
                                </td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <div class="badge @(item.IsNewfeed ? "badge-success" : "badge-dark") badge-dot m-r-10"></div>
                                        <div>IsNewfeed</div>
                                    </div>
                                </td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <div class="badge @(item.IsHot ? "badge-success" : "badge-dark") badge-dot m-r-10"></div>
                                        <div>IsHot</div>
                                    </div>
                                </td>

                                <td>
                                    <a asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Details" asp-route-id="@item.PostId" class="btn btn-primary btn-tone m-r-5">View</a>
                                    <a asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Edit" asp-route-id="@item.PostId" class="btn btn-secondary btn-tone m-r-5">Edit</a>
                                    <a asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Delete" asp-route-id="@item.PostId" class="btn btn-success btn-tone m-r-5">Delete</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>